
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class BuildDiff
{

    public long Id { get; set; }

    public int BuildId { get; set; }

    public Nullable<int> PreviousBuildDataId { get; set; }

    public Nullable<int> CurrentBuildDataId { get; set; }

    public string Diff { get; set; }



    public virtual BuildData CurrentBuildData { get; set; }

    public virtual BuildData PreviousBuildData { get; set; }

    public virtual Build Build { get; set; }

}

}
