
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class Build
{

    public Build()
    {

        this.BuildDatas = new HashSet<BuildData>();

        this.BuildDiffs = new HashSet<BuildDiff>();

        this.NextBuilds = new HashSet<Build>();

        this.BuildJiras = new HashSet<BuildJira>();

    }


    public int Id { get; set; }

    public int VMajor { get; set; }

    public int VMinor { get; set; }

    public int VPatch { get; set; }

    public Nullable<int> VBuild { get; set; }

    public string GitSha { get; set; }

    public Nullable<int> PreviousId { get; set; }

    public System.DateTime Created { get; set; }

    public System.DateTime Modified { get; set; }

    public bool Incomplete { get; set; }

    public bool JiraProcessed { get; set; }



    public virtual ICollection<BuildData> BuildDatas { get; set; }

    public virtual ICollection<BuildDiff> BuildDiffs { get; set; }

    public virtual ICollection<Build> NextBuilds { get; set; }

    public virtual Build PreviousBuild { get; set; }

    public virtual ICollection<BuildJira> BuildJiras { get; set; }

}

}
