

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class whatsgoingonEntities : DbContext
{
    public whatsgoingonEntities()
        : base("name=whatsgoingonEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<BuildData> BuildDatas { get; set; }

    public DbSet<Category> Categories { get; set; }

    public DbSet<BuildDiff> BuildDiffs { get; set; }

    public DbSet<Build> Builds { get; set; }

    public DbSet<BuildJira> BuildJiras { get; set; }

}

}

